### ISSUE TITLE
Breaking change in patch version? json_logging.init() -> json_logging.init_non_web()

### ISSUE THREAD

**Issue by vladcalin** [thangbn/json-logging-python#28]
I observed that there was introduced a breaking change in a patch version. Why would anybody do that? What's the point of using semantic versioning if releases don't respect the meaning of it? 
The change just breaks things and it would could have been avoided very easily by putting a line of code to preserve old behavior.

```
init = __init
```
And now there is no way to pass a custom formatter like before without calling the "private" __init method (about which every linter will complain)?

**Comment by thangbn** [comment]
@vladcalin sorry if the changes annoys you. 
The breaking change was introduced in 1.0.0 version: https://github.com/thangbn/json-logging-python/releases/tag/1.0.0. You can see why it jumped from 0.x.x to 1.x.x.
Anyways, if you want to pass customer formatter, you can do so in 1.0.3. Sorry that i overlooked the non web init method. please using **init_non_web** instead of **init** from now on.

**Comment by vladcalin** [comment]
I see that in the tagged version 1.0.0 (https://github.com/thangbn/json-logging-python/blob/1.0.0/json_logging/__init__.py) there still is the init() method, and in 1.0.1 it disappears, but it seems that in the 1.0.0 version from pypi there is no init() method, which makes it a pain.
Something doesn't add up here. It seems that git tags are not in sync with the pypi tags for some reason (at least for 1.0.0).
I am sorry for the rant, I just spent way too much time trying to figure out what happens in a library I use that uses unfrozen dependencies that crashes because of this.

**Comment by thangbn** [comment]
@vladcalin my bad, maybe I tagged it a bit too soon before I actually push my local changes up. Will be careful next time,
